version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - persist_to_workspace:
          root: dist/netocny
          paths:
            - ng-page-slider

    publish:
      executor:
        name: node/default
        tag: '12'
      steps:
        - attach_workspace:
            at: .

        - name: Publish to npmjs
          run: |
            cd dist/netocny/ng-page-slider/
            npm publish
workflows:
  build-and-test:
    jobs:
      - build
      - publish
